services:
  - type: web
    name: pakwheels-market-intelligence
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
